import { EmbeddingModel, LlmModel, VectorDbOption, WorkloadPreset } from './pricing.types';

export const PRICING_VERSION = '2026-08-01';

export const LLM_MODELS: LlmModel[] = [
  // ── OpenAI ─────────────────────────────────────────────────────────────────
  {
    id: 'gpt-4o',
    provider: 'openai',
    name: 'GPT-4o',
    category: 'llm',
    inputPricePer1M: 2.50,
    outputPricePer1M: 10.00,
    cachedInputPricePer1M: 1.25,
    batchInputPricePer1M: 1.25,
    batchOutputPricePer1M: 5.00,
    contextWindow: 128000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://openai.com/api/pricing',
  },
  {
    id: 'gpt-4o-mini',
    provider: 'openai',
    name: 'GPT-4o mini',
    category: 'llm',
    inputPricePer1M: 0.15,
    outputPricePer1M: 0.60,
    cachedInputPricePer1M: 0.075,
    batchInputPricePer1M: 0.075,
    batchOutputPricePer1M: 0.30,
    contextWindow: 128000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://openai.com/api/pricing',
  },
  {
    id: 'gpt-4-turbo',
    provider: 'openai',
    name: 'GPT-4 Turbo',
    category: 'llm',
    inputPricePer1M: 10.00,
    outputPricePer1M: 30.00,
    contextWindow: 128000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://openai.com/api/pricing',
  },
  {
    id: 'o1',
    provider: 'openai',
    name: 'o1',
    category: 'llm',
    inputPricePer1M: 15.00,
    outputPricePer1M: 60.00,
    cachedInputPricePer1M: 7.50,
    contextWindow: 200000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://openai.com/api/pricing',
    notes: 'Reasoning model; output tokens include reasoning tokens.',
  },
  {
    id: 'o1-mini',
    provider: 'openai',
    name: 'o1-mini',
    category: 'llm',
    inputPricePer1M: 3.00,
    outputPricePer1M: 12.00,
    cachedInputPricePer1M: 1.50,
    contextWindow: 128000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://openai.com/api/pricing',
    notes: 'Reasoning model.',
  },
  {
    id: 'o3-mini',
    provider: 'openai',
    name: 'o3-mini',
    category: 'llm',
    inputPricePer1M: 1.10,
    outputPricePer1M: 4.40,
    cachedInputPricePer1M: 0.55,
    contextWindow: 200000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://openai.com/api/pricing',
    notes: 'Reasoning model (medium effort pricing).',
  },

  // ── Anthropic ───────────────────────────────────────────────────────────────
  {
    id: 'claude-opus-4-8',
    provider: 'anthropic',
    name: 'Claude Opus 4.8',
    category: 'llm',
    inputPricePer1M: 15.00,
    outputPricePer1M: 75.00,
    cachedInputPricePer1M: 1.50,
    batchInputPricePer1M: 7.50,
    batchOutputPricePer1M: 37.50,
    contextWindow: 200000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://www.anthropic.com/pricing',
  },
  {
    id: 'claude-sonnet-4-6',
    provider: 'anthropic',
    name: 'Claude Sonnet 4.6',
    category: 'llm',
    inputPricePer1M: 3.00,
    outputPricePer1M: 15.00,
    cachedInputPricePer1M: 0.30,
    batchInputPricePer1M: 1.50,
    batchOutputPricePer1M: 7.50,
    contextWindow: 200000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://www.anthropic.com/pricing',
  },
  {
    id: 'claude-haiku-4-5',
    provider: 'anthropic',
    name: 'Claude Haiku 4.5',
    category: 'llm',
    inputPricePer1M: 0.80,
    outputPricePer1M: 4.00,
    cachedInputPricePer1M: 0.08,
    batchInputPricePer1M: 0.40,
    batchOutputPricePer1M: 2.00,
    contextWindow: 200000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://www.anthropic.com/pricing',
  },

  // ── Google ──────────────────────────────────────────────────────────────────
  {
    id: 'gemini-2-0-flash',
    provider: 'google',
    name: 'Gemini 2.0 Flash',
    category: 'llm',
    inputPricePer1M: 0.10,
    outputPricePer1M: 0.40,
    contextWindow: 1000000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://ai.google.dev/pricing',
  },
  {
    id: 'gemini-1-5-pro',
    provider: 'google',
    name: 'Gemini 1.5 Pro',
    category: 'llm',
    inputPricePer1M: 1.25,
    outputPricePer1M: 5.00,
    contextWindow: 2000000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://ai.google.dev/pricing',
    notes: 'Pricing shown for prompts ≤128K tokens.',
  },
  {
    id: 'gemini-1-5-flash',
    provider: 'google',
    name: 'Gemini 1.5 Flash',
    category: 'llm',
    inputPricePer1M: 0.075,
    outputPricePer1M: 0.30,
    contextWindow: 1000000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://ai.google.dev/pricing',
    notes: 'Pricing shown for prompts ≤128K tokens.',
  },

  // ── Mistral ──────────────────────────────────────────────────────────────────
  {
    id: 'mistral-large',
    provider: 'mistral',
    name: 'Mistral Large',
    category: 'llm',
    inputPricePer1M: 2.00,
    outputPricePer1M: 6.00,
    contextWindow: 128000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://mistral.ai/technology/#pricing',
  },
  {
    id: 'mistral-small',
    provider: 'mistral',
    name: 'Mistral Small',
    category: 'llm',
    inputPricePer1M: 0.20,
    outputPricePer1M: 0.60,
    contextWindow: 32000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://mistral.ai/technology/#pricing',
  },
  {
    id: 'codestral',
    provider: 'mistral',
    name: 'Codestral',
    category: 'llm',
    inputPricePer1M: 0.20,
    outputPricePer1M: 0.60,
    contextWindow: 32000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://mistral.ai/technology/#pricing',
  },

  // ── DeepSeek ─────────────────────────────────────────────────────────────────
  {
    id: 'deepseek-v3',
    provider: 'deepseek',
    name: 'DeepSeek V3',
    category: 'llm',
    inputPricePer1M: 0.27,
    outputPricePer1M: 1.10,
    cachedInputPricePer1M: 0.07,
    contextWindow: 64000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
  },
  {
    id: 'deepseek-r1',
    provider: 'deepseek',
    name: 'DeepSeek R1',
    category: 'llm',
    inputPricePer1M: 0.55,
    outputPricePer1M: 2.19,
    cachedInputPricePer1M: 0.14,
    contextWindow: 64000,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://api-docs.deepseek.com/quick_start/pricing',
    notes: 'Reasoning model.',
  },

  // ── Meta (via Together AI) ───────────────────────────────────────────────────
  {
    id: 'llama-3-1-70b',
    provider: 'meta',
    name: 'Llama 3.1 70B (Together)',
    category: 'llm',
    inputPricePer1M: 0.88,
    outputPricePer1M: 0.88,
    contextWindow: 131072,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://www.together.ai/pricing',
    notes: 'Pricing via Together AI. Self-hosting eliminates per-token cost.',
  },
  {
    id: 'llama-3-1-8b',
    provider: 'meta',
    name: 'Llama 3.1 8B (Together)',
    category: 'llm',
    inputPricePer1M: 0.18,
    outputPricePer1M: 0.18,
    contextWindow: 131072,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://www.together.ai/pricing',
    notes: 'Pricing via Together AI. Self-hosting eliminates per-token cost.',
  },
];

export const EMBEDDING_MODELS: EmbeddingModel[] = [
  {
    id: 'text-embedding-3-small',
    provider: 'openai',
    name: 'text-embedding-3-small',
    category: 'embedding',
    pricePer1M: 0.02,
    dimensions: 1536,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://openai.com/api/pricing',
  },
  {
    id: 'text-embedding-3-large',
    provider: 'openai',
    name: 'text-embedding-3-large',
    category: 'embedding',
    pricePer1M: 0.13,
    dimensions: 3072,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://openai.com/api/pricing',
  },
  {
    id: 'text-embedding-ada-002',
    provider: 'openai',
    name: 'text-embedding-ada-002',
    category: 'embedding',
    pricePer1M: 0.10,
    dimensions: 1536,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://openai.com/api/pricing',
  },
  {
    id: 'gemini-text-embedding-004',
    provider: 'google',
    name: 'Gemini text-embedding-004',
    category: 'embedding',
    pricePer1M: 0.00,
    dimensions: 768,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://ai.google.dev/pricing',
    // Free up to 100 RPM via AI Studio; Vertex AI charges may apply
  },
  {
    id: 'mistral-embed',
    provider: 'mistral',
    name: 'Mistral Embed',
    category: 'embedding',
    pricePer1M: 0.10,
    dimensions: 1024,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://mistral.ai/technology/#pricing',
  },
  {
    id: 'cohere-embed-v3',
    provider: 'cohere',
    name: 'Cohere Embed v3',
    category: 'embedding',
    pricePer1M: 0.10,
    dimensions: 1024,
    lastVerified: '2026-08-01',
    pricingUrl: 'https://cohere.com/pricing',
  },
];

export const VECTOR_DBS: VectorDbOption[] = [
  {
    id: 'pinecone-starter',
    name: 'Pinecone Starter',
    storagePricePerGbMonth: 0,
    queryPricePer1M: 0,
    freeTierGb: 1,
    notes: 'Free up to 1GB / 100K vectors.',
  },
  {
    id: 'pinecone-standard',
    name: 'Pinecone Standard',
    storagePricePerGbMonth: 0.096,
    queryPricePer1M: 8,
  },
  {
    id: 'weaviate-cloud',
    name: 'Weaviate Cloud',
    storagePricePerGbMonth: 0.095,
    queryPricePer1M: 5,
  },
  {
    id: 'qdrant-cloud',
    name: 'Qdrant Cloud',
    storagePricePerGbMonth: 0.024,
    queryPricePer1M: 4,
    freeTierGb: 1,
  },
  {
    id: 'self-hosted',
    name: 'Self-hosted (infra cost only)',
    storagePricePerGbMonth: 0.023,
    queryPricePer1M: 0,
    notes: 'AWS EBS gp3 ~$0.023/GB/month. Query cost is your compute bill.',
  },
  {
    id: 'supabase-pgvector',
    name: 'Supabase (pgvector)',
    storagePricePerGbMonth: 0.021,
    queryPricePer1M: 0,
    freeTierGb: 0.5,
    notes: 'Slower than dedicated vector DBs at scale; good for small corpora.',
  },
];

export const WORKLOAD_PRESETS: WorkloadPreset[] = [
  {
    id: 'chatbot',
    label: 'Simple Chatbot',
    inputTokens: 500,
    outputTokens: 300,
    requestsPerMonth: 50000,
    description: 'Basic Q&A assistant with short context.',
  },
  {
    id: 'rag-chatbot',
    label: 'RAG Chatbot',
    inputTokens: 2000,
    outputTokens: 500,
    requestsPerMonth: 30000,
    description: 'Retrieval-augmented chatbot with documents in context.',
  },
  {
    id: 'coding-assistant',
    label: 'Coding Assistant',
    inputTokens: 3000,
    outputTokens: 1000,
    requestsPerMonth: 20000,
    description: 'Code generation with large context windows.',
  },
  {
    id: 'support-copilot',
    label: 'Support Copilot',
    inputTokens: 1500,
    outputTokens: 400,
    requestsPerMonth: 100000,
    description: 'High-volume customer support automation.',
  },
  {
    id: 'document-summarizer',
    label: 'Document Summarizer',
    inputTokens: 8000,
    outputTokens: 500,
    requestsPerMonth: 10000,
    description: 'Batch document processing with long input.',
  },
];
